import { createContext, useState } from "react";

const AppContext = createContext(null);

const AppProvider = ({ children }) => {
    const [pointValues, setPointValues] = useState({
        passingYardValue: 0.04,
        passingTouchdownValue: 4,
        interceptionValue: -2,
        receivingYardValue: 0.1,
        rushingYardValue: 0.1,
        touchdownValue: 6,
        receptionValue: 1,
        fumbleValue: -2,
        sackValue: 0,
    });
    const [repLevels, setRepLevels] = useState({
        qbRepLevel: 12,
        wrRepLevel: 29,
        rbRepLevel: 29,
        flexRepLevel: 14,
        teRepLevel: 12
    });
    const [tiers, setTiers] = useState({
        tier1: 6,
        tier2: 4.5,
        tier3: 3,
        tier4: 2,
        tier5: 1,
        tier6: -0,
        tier7: -1
    });
    const [adpSetting, setAdpSetting] = useState('average');
    const [allPlayers, setAllPlayers] = useState([
    {
        rank: 0,
        name: "Ja'Marr Chase",
        team: "CIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 1,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 10,
        receivingYards: 1300,
        touchdowns: 10.5,
        receptions: 106.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "9%",
        averageAdp: 1,
        sleeperAdp: 1,
        espnAdp: 1,
        yahooAdp: 1,
        nflAdp: 1,
        ffCheatsheetAdp: 1
    },
    {
        rank: 0,
        name: "Bijan Robinson",
        team: "ATL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 3,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 1150,
        receivingYards: 350,
        touchdowns: 13,
        receptions: 45.5,
        fumbles: 1.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 3,
        sleeperAdp: 3,
        espnAdp: 2,
        yahooAdp: 3,
        nflAdp: 4,
        ffCheatsheetAdp: 2
    },
    {
        rank: 0,
        name: "Justin Jefferson",
        team: "MIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 5,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 1250,
        touchdowns: 9,
        receptions: 83,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "10%",
        averageAdp: 5,
        sleeperAdp: 4,
        espnAdp: 4,
        yahooAdp: 6,
        nflAdp: 5,
        ffCheatsheetAdp: 5
    },
    {
        rank: 0,
        name: "Ceedee Lamb",
        team: "DAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 5,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 75,
        receivingYards: 1160,
        touchdowns: 7.75,
        receptions: 91.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "4%",
        averageAdp: 5,
        sleeperAdp: 6,
        espnAdp: 6,
        yahooAdp: 7,
        nflAdp: 3,
        ffCheatsheetAdp: 6
    },
    {
        rank: 0,
        name: "Jahmyr Gibbs",
        team: "DET",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 5,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 1075,
        receivingYards: 425,
        touchdowns: 12.25,
        receptions: 53.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 5,
        sleeperAdp: 5,
        espnAdp: 5,
        yahooAdp: 4,
        nflAdp: 6,
        ffCheatsheetAdp: 4
    },
    {
        rank: 0,
        name: "Puka Nacua",
        team: "LAR",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 9,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 65,
        receivingYards: 1200,
        touchdowns: 6.5,
        receptions: 89,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "18%",
        averageAdp: 9,
        sleeperAdp: 8,
        espnAdp: 10,
        yahooAdp: 12,
        nflAdp: 7,
        ffCheatsheetAdp: 7
    },
    {
        rank: 0,
        name: "Malik Nabers",
        team: "NYG",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 10,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 1150,
        touchdowns: 7.25,
        receptions: 104,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 10,
        sleeperAdp: 9,
        espnAdp: 9,
        yahooAdp: 13,
        nflAdp: 10,
        ffCheatsheetAdp: 8
    },
    {
        rank: 0,
        name: "Amon-Ra St. Brown",
        team: "DET",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 10,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 15,
        receivingYards: 1075,
        touchdowns: 8.5,
        receptions: 97.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "3%",
        averageAdp: 10,
        sleeperAdp: 7,
        espnAdp: 8,
        yahooAdp: 11,
        nflAdp: 9,
        ffCheatsheetAdp: 9
    },
    {
        rank: 0,
        name: "Saquon Barkley",
        team: "PHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 3,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 1400,
        receivingYards: 275,
        touchdowns: 12.5,
        receptions: 40.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "13%",
        averageAdp: 3,
        sleeperAdp: 2,
        espnAdp: 3,
        yahooAdp: 3,
        nflAdp: 2,
        ffCheatsheetAdp: 3
    },
    {
        rank: 0,
        name: "Nico Collins",
        team: "HOU",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 14,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 1125,
        touchdowns: 7,
        receptions: 76,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "25%",
        averageAdp: 14,
        sleeperAdp: 12,
        espnAdp: 13,
        yahooAdp: 10,
        nflAdp: 16,
        ffCheatsheetAdp: 13
    },
    {
        rank: 0,
        name: "Brian Thomas Jr.",
        team: "JAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 15,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 45,
        receivingYards: 1150,
        touchdowns: 7,
        receptions: 78,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 15,
        sleeperAdp: 14,
        espnAdp: 16,
        yahooAdp: 16,
        nflAdp: 14,
        ffCheatsheetAdp: 14
    },
    {
        rank: 0,
        name: "Drake London",
        team: "ATL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 20,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 1113,
        touchdowns: 7.25,
        receptions: 87.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "2%",
        averageAdp: 20,
        sleeperAdp: 17,
        espnAdp: 21,
        yahooAdp: 21,
        nflAdp: 20,
        ffCheatsheetAdp: 19
    },
    {
        rank: 0,
        name: "Ashton Jeanty",
        team: "LV",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 10,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 1050,
        receivingYards: 355,
        touchdowns: 9.25,
        receptions: 46,
        fumbles: 1.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 10,
        sleeperAdp: 11,
        espnAdp: 11,
        yahooAdp: 12,
        nflAdp: 11,
        ffCheatsheetAdp: 10
    },
    {
        rank: 0,
        name: "De'Von Achane",
        team: "MIA",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 12,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 875,
        receivingYards: 405,
        touchdowns: 11.5,
        receptions: 54,
        fumbles: 0.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "18%",
        averageAdp: 12,
        sleeperAdp: 15,
        espnAdp: 14,
        yahooAdp: 16,
        nflAdp: 13,
        ffCheatsheetAdp: 15
    },
    {
        rank: 0,
        name: "Brock Bowers",
        team: "LV",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 19,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 10,
        receivingYards: 1010,
        touchdowns: 5,
        receptions: 94.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 19,
        sleeperAdp: 16,
        espnAdp: 20,
        yahooAdp: 21,
        nflAdp: 19,
        ffCheatsheetAdp: 16
    },
    {
        rank: 0,
        name: "A.J. Brown",
        team: "PHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 18,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 1125,
        touchdowns: 7.25,
        receptions: 71,
        fumbles: 1.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 18,
        sleeperAdp: 18,
        espnAdp: 18,
        yahooAdp: 21,
        nflAdp: 15,
        ffCheatsheetAdp: 20
    },
    {
        rank: 0,
        name: "Christian McCaffrey",
        team: "SF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 9,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 950,
        receivingYards: 425,
        touchdowns: 11.25,
        receptions: 48.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "35%",
        averageAdp: 9,
        sleeperAdp: 13,
        espnAdp: 7,
        yahooAdp: 9,
        nflAdp: 12,
        ffCheatsheetAdp: 11
    },
    {
        rank: 0,
        name: "Ladd McConkey",
        team: "LAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 26,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 1050,
        touchdowns: 6.25,
        receptions: 75,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 26,
        sleeperAdp: 22,
        espnAdp: 30,
        yahooAdp: 24,
        nflAdp: 23,
        ffCheatsheetAdp: 25
    },
    {
        rank: 0,
        name: "Trey McBride",
        team: "ARI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 27,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 900,
        touchdowns: 5,
        receptions: 88,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "4%",
        averageAdp: 27,
        sleeperAdp: 25,
        espnAdp: 25,
        yahooAdp: 29,
        nflAdp: 26,
        ffCheatsheetAdp: 26
    },
    {
        rank: 0,
        name: "Jaxon Smith-Njigba",
        team: "SEA",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 34,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 15,
        receivingYards: 975,
        touchdowns: 5.25,
        receptions: 90.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 34,
        sleeperAdp: 27,
        espnAdp: 37,
        yahooAdp: 34,
        nflAdp: 39,
        ffCheatsheetAdp: 29
    },
    {
        rank: 0,
        name: "Derrick Henry",
        team: "BAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 10,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 1325,
        receivingYards: 190,
        touchdowns: 13.5,
        receptions: 18.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "15%",
        averageAdp: 10,
        sleeperAdp: 10,
        espnAdp: 12,
        yahooAdp: 8,
        nflAdp: 8,
        ffCheatsheetAdp: 12
    },
    {
        rank: 0,
        name: "Garrett Wilson",
        team: "NYJ",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 37,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 955,
        touchdowns: 4.5,
        receptions: 87,
        fumbles: 2,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 37,
        sleeperAdp: 32,
        espnAdp: 41,
        yahooAdp: 38,
        nflAdp: 37,
        ffCheatsheetAdp: 33
    },
    {
        rank: 0,
        name: "Tee Higgins",
        team: "CIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 30,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 975,
        touchdowns: 7.25,
        receptions: 70,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "21%",
        averageAdp: 30,
        sleeperAdp: 30,
        espnAdp: 26,
        yahooAdp: 30,
        nflAdp: 31,
        ffCheatsheetAdp: 34
    },
    {
        rank: 0,
        name: "Josh Allen",
        team: "BUF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 23,
        bye: 0,
        position: "QB",
        passingYards: 3775,
        passingTouchdowns: 27.25,
        interceptions: 12.5,
        rushingYards: 495,
        receivingYards: 0,
        touchdowns: 10.25,
        receptions: 0,
        fumbles: 1.5,
        sacks: 21,
        fantasyScore: 0,
        drafted: false,
        injury: "1%",
        averageAdp: 23,
        sleeperAdp: 21,
        espnAdp: 19,
        yahooAdp: 21,
        nflAdp: 21,
        ffCheatsheetAdp: 22
    },
    {
        rank: 0,
        name: "Lamar Jackson",
        team: "BAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 21,
        bye: 0,
        position: "QB",
        passingYards: 3450,
        passingTouchdowns: 28.5,
        interceptions: 6.5,
        rushingYards: 780,
        receivingYards: 0,
        touchdowns: 4,
        receptions: 0,
        fumbles: 2,
        sacks: 33,
        fantasyScore: 0,
        drafted: false,
        injury: "16%",
        averageAdp: 21,
        sleeperAdp: 23,
        espnAdp: 23,
        yahooAdp: 22,
        nflAdp: 18,
        ffCheatsheetAdp: 24
    },
    {
        rank: 0,
        name: "Bucky Irving",
        team: "TB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 22,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 1000,
        receivingYards: 350,
        touchdowns: 7.5,
        receptions: 42,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 22,
        sleeperAdp: 19,
        espnAdp: 22,
        yahooAdp: 21,
        nflAdp: 25,
        ffCheatsheetAdp: 17
    },
    {
        rank: 0,
        name: "Rashee Rice",
        team: "KC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 50,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 950,
        touchdowns: 6.75,
        receptions: 80,
        fumbles: 0.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "41%",
        averageAdp: 54,
        sleeperAdp: 45,
        espnAdp: 75,
        yahooAdp: 60,
        nflAdp: 42,
        ffCheatsheetAdp: 47
    },
    {
        rank: 0,
        name: "Tyreek Hill",
        team: "MIA",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 29,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 20,
        receivingYards: 985,
        touchdowns: 7,
        receptions: 68.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "1%",
        averageAdp: 29,
        sleeperAdp: 26,
        espnAdp: 31,
        yahooAdp: 34,
        nflAdp: 36,
        ffCheatsheetAdp: 28
    },
    {
        rank: 0,
        name: "Chase Brown",
        team: "CIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 27,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 900,
        receivingYards: 330,
        touchdowns: 10.5,
        receptions: 49,
        fumbles: 0.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "18%",
        averageAdp: 27,
        sleeperAdp: 29,
        espnAdp: 24,
        yahooAdp: 26,
        nflAdp: 34,
        ffCheatsheetAdp: 23
    },
    {
        rank: 0,
        name: "Josh Jacobs",
        team: "GB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 17,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 1050,
        receivingYards: 270,
        touchdowns: 10,
        receptions: 33.5,
        fumbles: 1.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "9%",
        averageAdp: 17,
        sleeperAdp: 20,
        espnAdp: 17,
        yahooAdp: 17,
        nflAdp: 17,
        ffCheatsheetAdp: 18
    },
    {
        rank: 0,
        name: "Jayden Daniels",
        team: "WAS",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 31,
        bye: 0,
        position: "QB",
        passingYards: 3400,
        passingTouchdowns: 23.5,
        interceptions: 8.5,
        rushingYards: 700,
        receivingYards: 0,
        touchdowns: 5.75,
        receptions: 0,
        fumbles: 0.5,
        sacks: 45,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 31,
        sleeperAdp: 31,
        espnAdp: 27,
        yahooAdp: 29,
        nflAdp: 27,
        ffCheatsheetAdp: 31
    },
    {
        rank: 0,
        name: "Davante Adams",
        team: "LAR",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 39,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 950,
        touchdowns: 8,
        receptions: 76,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 39,
        sleeperAdp: 42,
        espnAdp: 34,
        yahooAdp: 40,
        nflAdp: 42,
        ffCheatsheetAdp: 40
    },
    {
        rank: 0,
        name: "Jonathan Taylor",
        team: "IND",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 20,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 1200,
        receivingYards: 200,
        touchdowns: 10,
        receptions: 26,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "24%",
        averageAdp: 20,
        sleeperAdp: 24,
        espnAdp: 15,
        yahooAdp: 16,
        nflAdp: 22,
        ffCheatsheetAdp: 21
    },
    {
        rank: 0,
        name: "George Kittle",
        team: "SF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 38,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 900,
        touchdowns: 6,
        receptions: 63.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 38,
        sleeperAdp: 38,
        espnAdp: 36,
        yahooAdp: 33,
        nflAdp: 38,
        ffCheatsheetAdp: 41
    },
    {
        rank: 0,
        name: "Mike Evans",
        team: "TB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 40,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 995,
        touchdowns: 7.5,
        receptions: 68,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "9%",
        averageAdp: 40,
        sleeperAdp: 37,
        espnAdp: 46,
        yahooAdp: 37,
        nflAdp: 33,
        ffCheatsheetAdp: 43
    },
    {
        rank: 0,
        name: "Terry Mclaurin",
        team: "WAS",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 39,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 975,
        touchdowns: 6.75,
        receptions: 73,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 39,
        sleeperAdp: 35,
        espnAdp: 35,
        yahooAdp: 41,
        nflAdp: 29,
        ffCheatsheetAdp: 39
    },
    {
        rank: 0,
        name: "Jalen Hurts",
        team: "PHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 37,
        bye: 0,
        position: "QB",
        passingYards: 3200,
        passingTouchdowns: 19.75,
        interceptions: 5.5,
        rushingYards: 600,
        receivingYards: 0,
        touchdowns: 12,
        receptions: 0,
        fumbles: 2,
        sacks: 33,
        fantasyScore: 0,
        drafted: false,
        injury: "9%",
        averageAdp: 37,
        sleeperAdp: 39,
        espnAdp: 28,
        yahooAdp: 34,
        nflAdp: 32,
        ffCheatsheetAdp: 42
    },
    {
        rank: 0,
        name: "Kyren Williams",
        team: "LAR",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 24,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 1000,
        receivingYards: 180,
        touchdowns: 13.5,
        receptions: 29,
        fumbles: 2,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "18%",
        averageAdp: 24,
        sleeperAdp: 28,
        espnAdp: 29,
        yahooAdp: 25,
        nflAdp: 24,
        ffCheatsheetAdp: 27
    },
    {
        rank: 0,
        name: "Breece Hall",
        team: "NYJ",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 33,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 850,
        receivingYards: 455,
        touchdowns: 8,
        receptions: 53.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "22%",
        averageAdp: 33,
        sleeperAdp: 33,
        espnAdp: 51,
        yahooAdp: 39,
        nflAdp: 30,
        ffCheatsheetAdp: 30
    },
    {
        rank: 0,
        name: "Alvin Kamara",
        team: "NO",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 38,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 763,
        receivingYards: 435,
        touchdowns: 6,
        receptions: 54.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "19%",
        averageAdp: 38,
        sleeperAdp: 41,
        espnAdp: 38,
        yahooAdp: 44,
        nflAdp: 46,
        ffCheatsheetAdp: 37
    },
    {
        rank: 0,
        name: "DJ Moore",
        team: "CHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 49,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 60,
        receivingYards: 975,
        touchdowns: 6,
        receptions: 69,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 49,
        sleeperAdp: 47,
        espnAdp: 55,
        yahooAdp: 57,
        nflAdp: 48,
        ffCheatsheetAdp: 46
    },
    {
        rank: 0,
        name: "Marvin Harrison Jr.",
        team: "ARI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 41,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 975,
        touchdowns: 7,
        receptions: 68.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 41,
        sleeperAdp: 36,
        espnAdp: 44,
        yahooAdp: 42,
        nflAdp: 43,
        ffCheatsheetAdp: 36
    },
    {
        rank: 0,
        name: "Kenneth Walker III",
        team: "SEA",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 38,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 850,
        receivingYards: 245,
        touchdowns: 7.25,
        receptions: 37.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "20%",
        averageAdp: 38,
        sleeperAdp: 44,
        espnAdp: 47,
        yahooAdp: 43,
        nflAdp: 40,
        ffCheatsheetAdp: 44
    },
    {
        rank: 0,
        name: "James Cook",
        team: "BUF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 32,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 950,
        receivingYards: 310,
        touchdowns: 12.25,
        receptions: 34.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "4%",
        averageAdp: 32,
        sleeperAdp: 34,
        espnAdp: 32,
        yahooAdp: 32,
        nflAdp: 28,
        ffCheatsheetAdp: 32
    },
    {
        rank: 0,
        name: "Courtland Sutton",
        team: "DEN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 53,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 875,
        touchdowns: 6.75,
        receptions: 67,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "4%",
        averageAdp: 53,
        sleeperAdp: 50,
        espnAdp: 58,
        yahooAdp: 60,
        nflAdp: 54,
        ffCheatsheetAdp: 49
    },
    {
        rank: 0,
        name: "Joe Burrow",
        team: "CIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 35,
        bye: 0,
        position: "QB",
        passingYards: 4200,
        passingTouchdowns: 33.75,
        interceptions: 11,
        rushingYards: 170,
        receivingYards: 0,
        touchdowns: 1.5,
        receptions: 0,
        fumbles: 0,
        sacks: 41,
        fantasyScore: 0,
        drafted: false,
        injury: "13%",
        averageAdp: 35,
        sleeperAdp: 40,
        espnAdp: 33,
        yahooAdp: 41,
        nflAdp: 35,
        ffCheatsheetAdp: 38
    },
    {
        rank: 0,
        name: "DK Metcalf",
        team: "PIT",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 50,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 940,
        touchdowns: 7,
        receptions: 62.5,
        fumbles: 2,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "4%",
        averageAdp: 50,
        sleeperAdp: 48,
        espnAdp: 43,
        yahooAdp: 50,
        nflAdp: 58,
        ffCheatsheetAdp: 50
    },
    {
        rank: 0,
        name: "DeVonta Smith",
        team: "PHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 56,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 850,
        touchdowns: 6,
        receptions: 67.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "7%",
        averageAdp: 56,
        sleeperAdp: 53,
        espnAdp: 61,
        yahooAdp: 59,
        nflAdp: 53,
        ffCheatsheetAdp: 52
    },
    {
        rank: 0,
        name: "Chuba Hubbard",
        team: "CAR",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 45,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 950,
        receivingYards: 245,
        touchdowns: 6.25,
        receptions: 41,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 45,
        sleeperAdp: 46,
        espnAdp: 40,
        yahooAdp: 42,
        nflAdp: 52,
        ffCheatsheetAdp: 45
    },
    {
        rank: 0,
        name: "Zay Flowers",
        team: "BAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 62,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 55,
        receivingYards: 900,
        touchdowns: 5,
        receptions: 71,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "3%",
        averageAdp: 62,
        sleeperAdp: 54,
        espnAdp: 54,
        yahooAdp: 61,
        nflAdp: 69,
        ffCheatsheetAdp: 60
    },
    {
        rank: 0,
        name: "James Conner",
        team: "ARI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 48,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 900,
        receivingYards: 335,
        touchdowns: 8.75,
        receptions: 42.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "16%",
        averageAdp: 48,
        sleeperAdp: 52,
        espnAdp: 45,
        yahooAdp: 48,
        nflAdp: 49,
        ffCheatsheetAdp: 48
    },
    {
        rank: 0,
        name: "Chris Olave",
        team: "NO",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 80,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 875,
        touchdowns: 4,
        receptions: 68,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "24%",
        averageAdp: 80,
        sleeperAdp: 70,
        espnAdp: 85,
        yahooAdp: 84,
        nflAdp: 87,
        ffCheatsheetAdp: 74
    },
    {
        rank: 0,
        name: "Joe Mixon",
        team: "HOU",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 53,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "10%",
        averageAdp: 66,
        sleeperAdp: 57,
        espnAdp: 142,
        yahooAdp: 62,
        nflAdp: 48,
        ffCheatsheetAdp: 51
    },
    {
        rank: 0,
        name: "Jaylen Waddle",
        team: "MIA",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 75,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 15,
        receivingYards: 925,
        touchdowns: 4.5,
        receptions: 65.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "9%",
        averageAdp: 75,
        sleeperAdp: 67,
        espnAdp: 65,
        yahooAdp: 76,
        nflAdp: 86,
        ffCheatsheetAdp: 75
    },
    {
        rank: 0,
        name: "Omarion Hampton",
        team: "LAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 43,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 870,
        receivingYards: 295,
        touchdowns: 7.75,
        receptions: 38.5,
        fumbles: 1.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 43,
        sleeperAdp: 45,
        espnAdp: 39,
        yahooAdp: 43,
        nflAdp: 50,
        ffCheatsheetAdp: 35
    },
    {
        rank: 0,
        name: "Chris Godwin",
        team: "TB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 80,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 720,
        touchdowns: 5,
        receptions: 62.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "22%",
        averageAdp: 80,
        sleeperAdp: 78,
        espnAdp: 110,
        yahooAdp: 90,
        nflAdp: 85,
        ffCheatsheetAdp: 76
    },
    {
        rank: 0,
        name: "Sam LaPorta",
        team: "DET",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 52,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 680,
        touchdowns: 6.25,
        receptions: 61.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "3%",
        averageAdp: 52,
        sleeperAdp: 49,
        espnAdp: 50,
        yahooAdp: 49,
        nflAdp: 44,
        ffCheatsheetAdp: 54
    },
    {
        rank: 0,
        name: "Tetairoa McMillan",
        team: "CAR",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 66,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 863,
        touchdowns: 5,
        receptions: 66.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 66,
        sleeperAdp: 62,
        espnAdp: 59,
        yahooAdp: 81,
        nflAdp: 77,
        ffCheatsheetAdp: 56
    },
    {
        rank: 0,
        name: "Patrick Mahomes",
        team: "KC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 53,
        bye: 0,
        position: "QB",
        passingYards: 4000,
        passingTouchdowns: 27.5,
        interceptions: 11,
        rushingYards: 315,
        receivingYards: 0,
        touchdowns: 2,
        receptions: 0,
        fumbles: 0,
        sacks: 26,
        fantasyScore: 0,
        drafted: false,
        injury: "3%",
        averageAdp: 53,
        sleeperAdp: 57,
        espnAdp: 42,
        yahooAdp: 51,
        nflAdp: 45,
        ffCheatsheetAdp: 59
    },
    {
        rank: 0,
        name: "Travis Hunter",
        team: "JAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 65,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 763,
        touchdowns: 4.25,
        receptions: 58,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 65,
        sleeperAdp: 64,
        espnAdp: 73,
        yahooAdp: 73,
        nflAdp: 59,
        ffCheatsheetAdp: 68
    },
    {
        rank: 0,
        name: "Jameson Williams",
        team: "DET",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 63,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 70,
        receivingYards: 875,
        touchdowns: 6.25,
        receptions: 52,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "26%",
        averageAdp: 63,
        sleeperAdp: 59,
        espnAdp: 66,
        yahooAdp: 68,
        nflAdp: 55,
        ffCheatsheetAdp: 62
    },
    {
        rank: 0,
        name: "David Montgomery",
        team: "DET",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 59,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 738,
        receivingYards: 295,
        touchdowns: 9.25,
        receptions: 31.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "16%",
        averageAdp: 59,
        sleeperAdp: 56,
        espnAdp: 60,
        yahooAdp: 51,
        nflAdp: 64,
        ffCheatsheetAdp: 58
    },
    {
        rank: 0,
        name: "Baker Mayfield",
        team: "TB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 64,
        bye: 0,
        position: "QB",
        passingYards: 3800,
        passingTouchdowns: 29,
        interceptions: 13.5,
        rushingYards: 170,
        receivingYards: 0,
        touchdowns: 2,
        receptions: 0,
        fumbles: 0.5,
        sacks: 38,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 64,
        sleeperAdp: 68,
        espnAdp: 52,
        yahooAdp: 61,
        nflAdp: 61,
        ffCheatsheetAdp: 73
    },
    {
        rank: 0,
        name: "Xavier Worthy",
        team: "KC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 57,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 100,
        receivingYards: 888,
        touchdowns: 7.75,
        receptions: 75.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 57,
        sleeperAdp: 55,
        espnAdp: 49,
        yahooAdp: 64,
        nflAdp: 66,
        ffCheatsheetAdp: 57
    },
    {
        rank: 0,
        name: "Jerry Jeudy",
        team: "CLE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 76,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 900,
        touchdowns: 3.5,
        receptions: 64.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "15%",
        averageAdp: 76,
        sleeperAdp: 73,
        espnAdp: 68,
        yahooAdp: 94,
        nflAdp: 101,
        ffCheatsheetAdp: 72
    },
    {
        rank: 0,
        name: "D'Andre Swift",
        team: "CHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 57,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 800,
        receivingYards: 320,
        touchdowns: 6,
        receptions: 39.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 57,
        sleeperAdp: 74,
        espnAdp: 53,
        yahooAdp: 72,
        nflAdp: 60,
        ffCheatsheetAdp: 61
    },
    {
        rank: 0,
        name: "Aaron Jones",
        team: "MIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 64,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 725,
        receivingYards: 260,
        touchdowns: 5.5,
        receptions: 33.5,
        fumbles: 3,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 64,
        sleeperAdp: 69,
        espnAdp: 70,
        yahooAdp: 73,
        nflAdp: 74,
        ffCheatsheetAdp: 63
    },
    {
        rank: 0,
        name: "RJ Harvey",
        team: "DEN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 64,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 750,
        receivingYards: 255,
        touchdowns: 6.75,
        receptions: 33,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 64,
        sleeperAdp: 61,
        espnAdp: 74,
        yahooAdp: 62,
        nflAdp: 71,
        ffCheatsheetAdp: 53
    },
    {
        rank: 0,
        name: "T.J. Hockenson",
        team: "MIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 63,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 725,
        touchdowns: 3,
        receptions: 68.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "21%",
        averageAdp: 63,
        sleeperAdp: 58,
        espnAdp: 57,
        yahooAdp: 59,
        nflAdp: 51,
        ffCheatsheetAdp: 64
    },
    {
        rank: 0,
        name: "George Pickens",
        team: "DAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 66,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 15,
        receivingYards: 888,
        touchdowns: 5.25,
        receptions: 57.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 66,
        sleeperAdp: 60,
        espnAdp: 69,
        yahooAdp: 68,
        nflAdp: 76,
        ffCheatsheetAdp: 65
    },
    {
        rank: 0,
        name: "TreVeyon Henderson",
        team: "NE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 62,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 700,
        receivingYards: 260,
        touchdowns: 4.75,
        receptions: 33.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "15%",
        averageAdp: 62,
        sleeperAdp: 65,
        espnAdp: 48,
        yahooAdp: 77,
        nflAdp: 67,
        ffCheatsheetAdp: 55
    },
    {
        rank: 0,
        name: "Calvin Ridley",
        team: "TEN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 69,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 20,
        receivingYards: 900,
        touchdowns: 5,
        receptions: 67,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "24%",
        averageAdp: 69,
        sleeperAdp: 75,
        espnAdp: 62,
        yahooAdp: 80,
        nflAdp: 72,
        ffCheatsheetAdp: 71
    },
    {
        rank: 0,
        name: "Bo Nix",
        team: "DEN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 74,
        bye: 0,
        position: "QB",
        passingYards: 3495,
        passingTouchdowns: 24.5,
        interceptions: 11,
        rushingYards: 400,
        receivingYards: 0,
        touchdowns: 3.5,
        receptions: 0,
        fumbles: 0.5,
        sacks: 22,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 74,
        sleeperAdp: 76,
        espnAdp: 67,
        yahooAdp: 69,
        nflAdp: 65,
        ffCheatsheetAdp: 78
    },
    {
        rank: 0,
        name: "Isiah Pacheco",
        team: "KC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 67,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 715,
        receivingYards: 180,
        touchdowns: 5,
        receptions: 27.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "25%",
        averageAdp: 67,
        sleeperAdp: 63,
        espnAdp: 64,
        yahooAdp: 66,
        nflAdp: 62,
        ffCheatsheetAdp: 66
    },
    {
        rank: 0,
        name: "Tony Pollard",
        team: "TEN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 75,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 900,
        receivingYards: 230,
        touchdowns: 5,
        receptions: 39.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 75,
        sleeperAdp: 77,
        espnAdp: 63,
        yahooAdp: 65,
        nflAdp: 82,
        ffCheatsheetAdp: 70
    },
    {
        rank: 0,
        name: "Jordan Addison",
        team: "MIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 85,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 10,
        receivingYards: 730,
        touchdowns: 7.25,
        receptions: 54.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 85,
        sleeperAdp: 71,
        espnAdp: 109,
        yahooAdp: 94,
        nflAdp: 92,
        ffCheatsheetAdp: 77
    },
    {
        rank: 0,
        name: "Kyler Murray",
        team: "ARI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 87,
        bye: 0,
        position: "QB",
        passingYards: 3395,
        passingTouchdowns: 20.5,
        interceptions: 9.5,
        rushingYards: 500,
        receivingYards: 0,
        touchdowns: 4,
        receptions: 0,
        fumbles: 2.5,
        sacks: 34,
        fantasyScore: 0,
        drafted: false,
        injury: "26%",
        averageAdp: 87,
        sleeperAdp: 97,
        espnAdp: 77,
        yahooAdp: 96,
        nflAdp: 81,
        ffCheatsheetAdp: 90
    },
    {
        rank: 0,
        name: "Travis Kelce",
        team: "KC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 61,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 713,
        touchdowns: 5,
        receptions: 67.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 61,
        sleeperAdp: 66,
        espnAdp: 56,
        yahooAdp: 62,
        nflAdp: 57,
        ffCheatsheetAdp: 69
    },
    {
        rank: 0,
        name: "Evan Engram",
        team: "DEN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 87,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 575,
        touchdowns: 2.5,
        receptions: 68.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "15%",
        averageAdp: 87,
        sleeperAdp: 87,
        espnAdp: 79,
        yahooAdp: 87,
        nflAdp: 75,
        ffCheatsheetAdp: 87
    },
    {
        rank: 0,
        name: "Rome Odunze",
        team: "CHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 84,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 15,
        receivingYards: 850,
        touchdowns: 5,
        receptions: 62.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 84,
        sleeperAdp: 80,
        espnAdp: 76,
        yahooAdp: 89,
        nflAdp: 93,
        ffCheatsheetAdp: 80
    },
    {
        rank: 0,
        name: "Khalil Shakir",
        team: "BUF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 98,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 775,
        touchdowns: 3.75,
        receptions: 61,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 98,
        sleeperAdp: 84,
        espnAdp: 111,
        yahooAdp: 118,
        nflAdp: 100,
        ffCheatsheetAdp: 89
    },
    {
        rank: 0,
        name: "Kaleb Johnson",
        team: "PIT",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 71,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 715,
        receivingYards: 240,
        touchdowns: 6.5,
        receptions: 31.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "10%",
        averageAdp: 71,
        sleeperAdp: 81,
        espnAdp: 98,
        yahooAdp: 68,
        nflAdp: 80,
        ffCheatsheetAdp: 67
    },
    {
        rank: 0,
        name: "Jauan Jennings",
        team: "SF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 100,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 900,
        touchdowns: 4.5,
        receptions: 71,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 100,
        sleeperAdp: 95,
        espnAdp: 114,
        yahooAdp: 105,
        nflAdp: 108,
        ffCheatsheetAdp: 93
    },
    {
        rank: 0,
        name: "Jakobi Meyers",
        team: "LV",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 94,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 20,
        receivingYards: 813,
        touchdowns: 4.5,
        receptions: 69,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "9%",
        averageAdp: 94,
        sleeperAdp: 82,
        espnAdp: 83,
        yahooAdp: 108,
        nflAdp: 125,
        ffCheatsheetAdp: 92
    },
    {
        rank: 0,
        name: "David Njoku",
        team: "CLE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 88,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 678,
        touchdowns: 5.25,
        receptions: 63,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "16%",
        averageAdp: 88,
        sleeperAdp: 93,
        espnAdp: 71,
        yahooAdp: 79,
        nflAdp: 84,
        ffCheatsheetAdp: 100
    },
    {
        rank: 0,
        name: "Jaylen Warren",
        team: "PIT",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 93,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 575,
        receivingYards: 325,
        touchdowns: 1.5,
        receptions: 42.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 93,
        sleeperAdp: 92,
        espnAdp: 84,
        yahooAdp: 95,
        nflAdp: 109,
        ffCheatsheetAdp: 85
    },
    {
        rank: 0,
        name: "Mark Andrews",
        team: "BAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 75,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 605,
        touchdowns: 6.5,
        receptions: 50,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "13%",
        averageAdp: 75,
        sleeperAdp: 79,
        espnAdp: 72,
        yahooAdp: 63,
        nflAdp: 56,
        ffCheatsheetAdp: 84
    },
    {
        rank: 0,
        name: "Justin Fields",
        team: "NYJ",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 109,
        bye: 0,
        position: "QB",
        passingYards: 2500,
        passingTouchdowns: 14,
        interceptions: 8.5,
        rushingYards: 663,
        receivingYards: 0,
        touchdowns: 6,
        receptions: 0,
        fumbles: 0,
        sacks: 43,
        fantasyScore: 0,
        drafted: false,
        injury: "16%",
        averageAdp: 109,
        sleeperAdp: 140,
        espnAdp: 125,
        yahooAdp: 82,
        nflAdp: 63,
        ffCheatsheetAdp: 110
    },
    {
        rank: 0,
        name: "Brian Robinson Jr.",
        team: "WAS",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 83,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 725,
        receivingYards: 145,
        touchdowns: 7.25,
        receptions: 18,
        fumbles: 2,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "20%",
        averageAdp: 83,
        sleeperAdp: 83,
        espnAdp: 91,
        yahooAdp: 87,
        nflAdp: 91,
        ffCheatsheetAdp: 81
    },
    {
        rank: 0,
        name: "Stefon Diggs",
        team: "NE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 89,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 750,
        touchdowns: 5,
        receptions: 67.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "15%",
        averageAdp: 89,
        sleeperAdp: 89,
        espnAdp: 88,
        yahooAdp: 104,
        nflAdp: 96,
        ffCheatsheetAdp: 91
    },
    {
        rank: 0,
        name: "Brock Purdy",
        team: "SF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 105,
        bye: 0,
        position: "QB",
        passingYards: 3850,
        passingTouchdowns: 24,
        interceptions: 11,
        rushingYards: 130,
        receivingYards: 0,
        touchdowns: 2,
        receptions: 0,
        fumbles: 0,
        sacks: 31,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 105,
        sleeperAdp: 109,
        espnAdp: 78,
        yahooAdp: 81,
        nflAdp: 104,
        ffCheatsheetAdp: 106
    },
    {
        rank: 0,
        name: "Travis Etienne Jr.",
        team: "JAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 101,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 505,
        receivingYards: 230,
        touchdowns: 2.25,
        receptions: 28,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "4%",
        averageAdp: 101,
        sleeperAdp: 94,
        espnAdp: 116,
        yahooAdp: 111,
        nflAdp: 114,
        ffCheatsheetAdp: 88
    },
    {
        rank: 0,
        name: "Caleb Williams",
        team: "CHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 115,
        bye: 0,
        position: "QB",
        passingYards: 3600,
        passingTouchdowns: 23,
        interceptions: 6,
        rushingYards: 400,
        receivingYards: 0,
        touchdowns: 0.5,
        receptions: 0,
        fumbles: 2,
        sacks: 69,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 115,
        sleeperAdp: 120,
        espnAdp: 112,
        yahooAdp: 113,
        nflAdp: 111,
        ffCheatsheetAdp: 103
    },
    {
        rank: 0,
        name: "Dak Prescott",
        team: "DAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 107,
        bye: 0,
        position: "QB",
        passingYards: 3875,
        passingTouchdowns: 26.25,
        interceptions: 12.5,
        rushingYards: 210,
        receivingYards: 0,
        touchdowns: 1.5,
        receptions: 0,
        fumbles: 1,
        sacks: 33,
        fantasyScore: 0,
        drafted: false,
        injury: "22%",
        averageAdp: 107,
        sleeperAdp: 121,
        espnAdp: 99,
        yahooAdp: 101,
        nflAdp: 119,
        ffCheatsheetAdp: 105
    },
    {
        rank: 0,
        name: "Josh Downs",
        team: "IND",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 124,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 675,
        touchdowns: 3,
        receptions: 60,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "9%",
        averageAdp: 124,
        sleeperAdp: 102,
        espnAdp: 133,
        yahooAdp: 123,
        nflAdp: 136,
        ffCheatsheetAdp: 111
    },
    {
        rank: 0,
        name: "Justin Herbert",
        team: "LAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 113,
        bye: 0,
        position: "QB",
        passingYards: 3650,
        passingTouchdowns: 22.5,
        interceptions: 7.5,
        rushingYards: 265,
        receivingYards: 0,
        touchdowns: 2,
        receptions: 0,
        fumbles: 0,
        sacks: 34,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 113,
        sleeperAdp: 103,
        espnAdp: 93,
        yahooAdp: 104,
        nflAdp: 126,
        ffCheatsheetAdp: 112
    },
    {
        rank: 0,
        name: "Tyrone Tracy Jr.",
        team: "NYG",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 91,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 725,
        receivingYards: 245,
        touchdowns: 5.5,
        receptions: 33,
        fumbles: 1.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 91,
        sleeperAdp: 85,
        espnAdp: 81,
        yahooAdp: 94,
        nflAdp: 106,
        ffCheatsheetAdp: 79
    },
    {
        rank: 0,
        name: "Quinshon Judkins",
        team: "CLE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 96,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 96,
        sleeperAdp: 72,
        espnAdp: 141,
        yahooAdp: 102,
        nflAdp: 89,
        ffCheatsheetAdp: 0
    },
    {
        rank: 0,
        name: "Jared Goff",
        team: "DET",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 104,
        bye: 0,
        position: "QB",
        passingYards: 3875,
        passingTouchdowns: 28.25,
        interceptions: 10,
        rushingYards: 45,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 1,
        sacks: 25,
        fantasyScore: 0,
        drafted: false,
        injury: "4%",
        averageAdp: 104,
        sleeperAdp: 91,
        espnAdp: 127,
        yahooAdp: 102,
        nflAdp: 99,
        ffCheatsheetAdp: 96
    },
    {
        rank: 0,
        name: "Michael Pittman Jr.",
        team: "IND",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 128,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 750,
        touchdowns: 2.75,
        receptions: 71,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "4%",
        averageAdp: 128,
        sleeperAdp: 116,
        espnAdp: 94,
        yahooAdp: 129,
        nflAdp: 175,
        ffCheatsheetAdp: 116
    },
    {
        rank: 0,
        name: "Deebo Samuel",
        team: "WAS",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 89,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 175,
        receivingYards: 700,
        touchdowns: 6.25,
        receptions: 53.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "13%",
        averageAdp: 89,
        sleeperAdp: 86,
        espnAdp: 96,
        yahooAdp: 104,
        nflAdp: 98,
        ffCheatsheetAdp: 83
    },
    {
        rank: 0,
        name: "Jayden Reed",
        team: "GB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 110,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 120,
        receivingYards: 688,
        touchdowns: 6.5,
        receptions: 49.5,
        fumbles: 0.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "3%",
        averageAdp: 110,
        sleeperAdp: 98,
        espnAdp: 130,
        yahooAdp: 103,
        nflAdp: 122,
        ffCheatsheetAdp: 98
    },
    {
        rank: 0,
        name: "Ricky Pearsall",
        team: "SF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 105,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 80,
        receivingYards: 850,
        touchdowns: 5.5,
        receptions: 66,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "35%",
        averageAdp: 105,
        sleeperAdp: 101,
        espnAdp: 87,
        yahooAdp: 111,
        nflAdp: 118,
        ffCheatsheetAdp: 99
    },
    {
        rank: 0,
        name: "Javonte Williams",
        team: "DAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 104,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 525,
        receivingYards: 195,
        touchdowns: 3.5,
        receptions: 40,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "21%",
        averageAdp: 104,
        sleeperAdp: 105,
        espnAdp: 101,
        yahooAdp: 125,
        nflAdp: 141,
        ffCheatsheetAdp: 97
    },
    {
        rank: 0,
        name: "Tucker Kraft",
        team: "GB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 116,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 625,
        touchdowns: 3.5,
        receptions: 47.5,
        fumbles: 0.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 116,
        sleeperAdp: 117,
        espnAdp: 106,
        yahooAdp: 98,
        nflAdp: 117,
        ffCheatsheetAdp: 114
    },
    {
        rank: 0,
        name: "Cooper Kupp",
        team: "SEA",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 88,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 10,
        receivingYards: 670,
        touchdowns: 5,
        receptions: 62,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "26%",
        averageAdp: 88,
        sleeperAdp: 88,
        espnAdp: 91,
        yahooAdp: 113,
        nflAdp: 105,
        ffCheatsheetAdp: 86
    },
    {
        rank: 0,
        name: "Drake Maye",
        team: "NE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 147,
        bye: 0,
        position: "QB",
        passingYards: 3300,
        passingTouchdowns: 19.75,
        interceptions: 13.5,
        rushingYards: 500,
        receivingYards: 0,
        touchdowns: 2.5,
        receptions: 0,
        fumbles: 2,
        sacks: 49,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 147,
        sleeperAdp: 142,
        espnAdp: 118,
        yahooAdp: 117,
        nflAdp: 146,
        ffCheatsheetAdp: 128
    },
    {
        rank: 0,
        name: "Jordan Love",
        team: "GB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 132,
        bye: 0,
        position: "QB",
        passingYards: 3600,
        passingTouchdowns: 25.5,
        interceptions: 11,
        rushingYards: 155,
        receivingYards: 0,
        touchdowns: 2,
        receptions: 0,
        fumbles: 1,
        sacks: 21,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 132,
        sleeperAdp: 126,
        espnAdp: 123,
        yahooAdp: 117,
        nflAdp: 134,
        ffCheatsheetAdp: 126
    },
    {
        rank: 0,
        name: "Najee Harris",
        team: "LAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 116,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 116,
        sleeperAdp: 106,
        espnAdp: 159,
        yahooAdp: 116,
        nflAdp: 113,
        ffCheatsheetAdp: 0
    },
    {
        rank: 0,
        name: "Jake Ferguson",
        team: "DAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 136,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 525,
        touchdowns: 2.75,
        receptions: 54.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "8%",
        averageAdp: 136,
        sleeperAdp: 122,
        espnAdp: 137,
        yahooAdp: 118,
        nflAdp: 152,
        ffCheatsheetAdp: 125
    },
    {
        rank: 0,
        name: "Trevor Lawrence",
        team: "JAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 171,
        bye: 0,
        position: "QB",
        passingYards: 3650,
        passingTouchdowns: 21.75,
        interceptions: 12.5,
        rushingYards: 260,
        receivingYards: 0,
        touchdowns: 4.25,
        receptions: 0,
        fumbles: 1.5,
        sacks: 32,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 171,
        sleeperAdp: 171,
        espnAdp: 181,
        yahooAdp: 131,
        nflAdp: 184,
        ffCheatsheetAdp: 142
    },
    {
        rank: 0,
        name: "Dalton Kincaid",
        team: "BUF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 133,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 600,
        touchdowns: 3.75,
        receptions: 62.5,
        fumbles: 0.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "15%",
        averageAdp: 133,
        sleeperAdp: 113,
        espnAdp: 128,
        yahooAdp: 115,
        nflAdp: 128,
        ffCheatsheetAdp: 123
    },
    {
        rank: 0,
        name: "C.J. Stroud",
        team: "HOU",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 138,
        bye: 0,
        position: "QB",
        passingYards: 3750,
        passingTouchdowns: 21.5,
        interceptions: 8,
        rushingYards: 190,
        receivingYards: 0,
        touchdowns: 1.5,
        receptions: 0,
        fumbles: 1.5,
        sacks: 43,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 138,
        sleeperAdp: 123,
        espnAdp: 124,
        yahooAdp: 121,
        nflAdp: 133,
        ffCheatsheetAdp: 130
    },
    {
        rank: 0,
        name: "Zach Charbonnet",
        team: "SEA",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 123,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 500,
        receivingYards: 265,
        touchdowns: 4.5,
        receptions: 36,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "3%",
        averageAdp: 123,
        sleeperAdp: 112,
        espnAdp: 126,
        yahooAdp: 115,
        nflAdp: 156,
        ffCheatsheetAdp: 102
    },
    {
        rank: 0,
        name: "Darnell Mooney",
        team: "ATL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 132,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 675,
        touchdowns: 2.75,
        receptions: 50.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 132,
        sleeperAdp: 111,
        espnAdp: 139,
        yahooAdp: 132,
        nflAdp: 170,
        ffCheatsheetAdp: 120
    },
    {
        rank: 0,
        name: "Brandon Aiyuk",
        team: "SF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 124,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "16%",
        averageAdp: 124,
        sleeperAdp: 104,
        espnAdp: 162,
        yahooAdp: 127,
        nflAdp: 120,
        ffCheatsheetAdp: 0
    },
    {
        rank: 0,
        name: "Rhamondre Stevenson",
        team: "NE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 112,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 675,
        receivingYards: 210,
        touchdowns: 6,
        receptions: 35,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "18%",
        averageAdp: 112,
        sleeperAdp: 114,
        espnAdp: 105,
        yahooAdp: 116,
        nflAdp: 123,
        ffCheatsheetAdp: 108
    },
    {
        rank: 0,
        name: "Cam Skattebo",
        team: "NYG",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 94,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 475,
        receivingYards: 160,
        touchdowns: 6,
        receptions: 21,
        fumbles: 0.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 94,
        sleeperAdp: 100,
        espnAdp: 102,
        yahooAdp: 114,
        nflAdp: 97,
        ffCheatsheetAdp: 94
    },
    {
        rank: 0,
        name: "Tyjae Spears",
        team: "TEN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 133,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 450,
        receivingYards: 360,
        touchdowns: 4.75,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "15%",
        averageAdp: 133,
        sleeperAdp: 125,
        espnAdp: 138,
        yahooAdp: 129,
        nflAdp: 174,
        ffCheatsheetAdp: 107
    },
    {
        rank: 0,
        name: "Jordan Mason",
        team: "MIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 119,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 600,
        receivingYards: 70,
        touchdowns: 2.25,
        receptions: 8,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "12%",
        averageAdp: 119,
        sleeperAdp: 110,
        espnAdp: 119,
        yahooAdp: 100,
        nflAdp: 145,
        ffCheatsheetAdp: 104
    },
    {
        rank: 0,
        name: "Dallas Goedert",
        team: "PHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 134,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 575,
        touchdowns: 2.5,
        receptions: 48.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "25%",
        averageAdp: 134,
        sleeperAdp: 127,
        espnAdp: 129,
        yahooAdp: 116,
        nflAdp: 130,
        ffCheatsheetAdp: 135
    },
    {
        rank: 0,
        name: "Rachaad White",
        team: "TB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 133,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 415,
        receivingYards: 250,
        touchdowns: 3.75,
        receptions: 32.5,
        fumbles: 3,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "2%",
        averageAdp: 133,
        sleeperAdp: 139,
        espnAdp: 140,
        yahooAdp: 129,
        nflAdp: 138,
        ffCheatsheetAdp: 124
    },
    {
        rank: 0,
        name: "Tyler Warren",
        team: "IND",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 93,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 538,
        touchdowns: 3.5,
        receptions: 49.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 93,
        sleeperAdp: 92,
        espnAdp: 90,
        yahooAdp: 120,
        nflAdp: 109,
        ffCheatsheetAdp: 109
    },
    {
        rank: 0,
        name: "Emeka Egbuka",
        team: "TB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 123,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 30,
        receivingYards: 750,
        touchdowns: 4,
        receptions: 57.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "7%",
        averageAdp: 123,
        sleeperAdp: 108,
        espnAdp: 82,
        yahooAdp: 116,
        nflAdp: 157,
        ffCheatsheetAdp: 119
    },
    {
        rank: 0,
        name: "J.J. McCarthy",
        team: "MIN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 147,
        bye: 0,
        position: "QB",
        passingYards: 3650,
        passingTouchdowns: 24.5,
        interceptions: 10.5,
        rushingYards: 370,
        receivingYards: 0,
        touchdowns: 0.5,
        receptions: 0,
        fumbles: 1.5,
        sacks: 37,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 147,
        sleeperAdp: 145,
        espnAdp: 136,
        yahooAdp: 123,
        nflAdp: 151,
        ffCheatsheetAdp: 131
    },
    {
        rank: 0,
        name: "Christian Kirk",
        team: "HOU",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 171,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 550,
        touchdowns: 2,
        receptions: 40,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "21%",
        averageAdp: 171,
        sleeperAdp: 148,
        espnAdp: 239,
        yahooAdp: 132,
        nflAdp: 169,
        ffCheatsheetAdp: 146
    },
    {
        rank: 0,
        name: "Tua Tagovailoa",
        team: "MIA",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 168,
        bye: 0,
        position: "QB",
        passingYards: 3490,
        passingTouchdowns: 23.25,
        interceptions: 8.5,
        rushingYards: 60,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0.5,
        sacks: 22,
        fantasyScore: 0,
        drafted: false,
        injury: "21%",
        averageAdp: 168,
        sleeperAdp: 195,
        espnAdp: 164,
        yahooAdp: 126,
        nflAdp: 192,
        ffCheatsheetAdp: 150
    },
    {
        rank: 0,
        name: "Matthew Stafford",
        team: "LAR",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 183,
        bye: 0,
        position: "QB",
        passingYards: 3750,
        passingTouchdowns: 23.25,
        interceptions: 10.5,
        rushingYards: 40,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 28,
        fantasyScore: 0,
        drafted: false,
        injury: "16%",
        averageAdp: 183,
        sleeperAdp: 193,
        espnAdp: 165,
        yahooAdp: 127,
        nflAdp: 160,
        ffCheatsheetAdp: 159
    },
    {
        rank: 0,
        name: "Keon Coleman",
        team: "BUF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 124,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 10,
        receivingYards: 740,
        touchdowns: 5.25,
        receptions: 39,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "24%",
        averageAdp: 124,
        sleeperAdp: 118,
        espnAdp: 108,
        yahooAdp: 129,
        nflAdp: 144,
        ffCheatsheetAdp: 127
    },
    {
        rank: 0,
        name: "Matthew Golden",
        team: "GB",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 103,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 700,
        touchdowns: 4.5,
        receptions: 54,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "14%",
        averageAdp: 103,
        sleeperAdp: 99,
        espnAdp: 80,
        yahooAdp: 121,
        nflAdp: 124,
        ffCheatsheetAdp: 95
    },
    {
        rank: 0,
        name: "Rashid Shaheed",
        team: "NO",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 155,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 60,
        receivingYards: 725,
        touchdowns: 3,
        receptions: 42,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "35%",
        averageAdp: 155,
        sleeperAdp: 138,
        espnAdp: 135,
        yahooAdp: 131,
        nflAdp: 182,
        ffCheatsheetAdp: 141
    },
    {
        rank: 0,
        name: "Tank Bigsby",
        team: "JAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 142,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 675,
        receivingYards: 45,
        touchdowns: 6.75,
        receptions: 6,
        fumbles: 1.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "3%",
        averageAdp: 142,
        sleeperAdp: 146,
        espnAdp: 134,
        yahooAdp: 120,
        nflAdp: 208,
        ffCheatsheetAdp: 122
    },
    {
        rank: 0,
        name: "Austin Ekeler",
        team: "WAS",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 139,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "13%",
        averageAdp: 139,
        sleeperAdp: 165,
        espnAdp: 95,
        yahooAdp: 129,
        nflAdp: 166,
        ffCheatsheetAdp: 0
    },
    {
        rank: 0,
        name: "Jonnu Smith",
        team: "PIT",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 118,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 600,
        touchdowns: 3,
        receptions: 60,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 118,
        sleeperAdp: 90,
        espnAdp: 169,
        yahooAdp: 116,
        nflAdp: 73,
        ffCheatsheetAdp: 115
    },
    {
        rank: 0,
        name: "J.K. Dobbins",
        team: "DEN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 117,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "57%",
        averageAdp: 117,
        sleeperAdp: 119,
        espnAdp: 97,
        yahooAdp: 114,
        nflAdp: 161,
        ffCheatsheetAdp: 0
    },
    {
        rank: 0,
        name: "Bryce Young",
        team: "CAR",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 189,
        bye: 0,
        position: "QB",
        passingYards: 3190,
        passingTouchdowns: 18,
        interceptions: 11,
        rushingYards: 300,
        receivingYards: 0,
        touchdowns: 4,
        receptions: 0,
        fumbles: 0.5,
        sacks: 55,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 189,
        sleeperAdp: 189,
        espnAdp: 186,
        yahooAdp: 127,
        nflAdp: 187,
        ffCheatsheetAdp: 162
    },
    {
        rank: 0,
        name: "Colston Loveland",
        team: "CHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 114,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 600,
        touchdowns: 3.75,
        receptions: 55,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "5%",
        averageAdp: 114,
        sleeperAdp: 107,
        espnAdp: 113,
        yahooAdp: 125,
        nflAdp: 116,
        ffCheatsheetAdp: 117
    },
    {
        rank: 0,
        name: "Hunter Henry",
        team: "NE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 174,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 174,
        sleeperAdp: 169,
        espnAdp: 160,
        yahooAdp: 127,
        nflAdp: 172,
        ffCheatsheetAdp: 0
    },
    {
        rank: 0,
        name: "Cedric Tillman",
        team: "CLE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 211,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 650,
        touchdowns: 3.5,
        receptions: 57.5,
        fumbles: 0.5,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "26%",
        averageAdp: 211,
        sleeperAdp: 188,
        espnAdp: 178,
        yahooAdp: 145,
        nflAdp: 322,
        ffCheatsheetAdp: 171
    },
    {
        rank: 0,
        name: "Ray Davis",
        team: "BUF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 175,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 450,
        receivingYards: 190,
        touchdowns: 5.5,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 175,
        sleeperAdp: 168,
        espnAdp: 219,
        yahooAdp: 130,
        nflAdp: 218,
        ffCheatsheetAdp: 140
    },
    {
        rank: 0,
        name: "Luther Burden III",
        team: "CHI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 164,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 164,
        sleeperAdp: 144,
        espnAdp: 173,
        yahooAdp: 129,
        nflAdp: 211,
        ffCheatsheetAdp: 0
    },
    {
        rank: 0,
        name: "Michael Penix Jr.",
        team: "ATL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 180,
        bye: 0,
        position: "QB",
        passingYards: 3385,
        passingTouchdowns: 19,
        interceptions: 12.5,
        rushingYards: 50,
        receivingYards: 0,
        touchdowns: 0.5,
        receptions: 0,
        fumbles: 0.5,
        sacks: 34,
        fantasyScore: 0,
        drafted: false,
        injury: "0%",
        averageAdp: 180,
        sleeperAdp: 172,
        espnAdp: 182,
        yahooAdp: 125,
        nflAdp: 185,
        ffCheatsheetAdp: 155
    },
    {
        rank: 0,
        name: "Rashod Bateman",
        team: "BAL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 176,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 550,
        touchdowns: 4,
        receptions: 33,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "25%",
        averageAdp: 176,
        sleeperAdp: 164,
        espnAdp: 185,
        yahooAdp: 130,
        nflAdp: 183,
        ffCheatsheetAdp: 165
    },
    {
        rank: 0,
        name: "Marquise Brown",
        team: "KC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 167,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 555,
        touchdowns: 3.25,
        receptions: 52.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "35%",
        averageAdp: 167,
        sleeperAdp: 174,
        espnAdp: 177,
        yahooAdp: 129,
        nflAdp: 115,
        ffCheatsheetAdp: 148
    },
    {
        rank: 0,
        name: "Trey Benson",
        team: "ARI",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 162,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 450,
        receivingYards: 90,
        touchdowns: 1.5,
        receptions: 9,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "24%",
        averageAdp: 162,
        sleeperAdp: 167,
        espnAdp: 155,
        yahooAdp: 131,
        nflAdp: 227,
        ffCheatsheetAdp: 143
    },
    {
        rank: 0,
        name: "Rico Dowdle",
        team: "CAR",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 182,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 182,
        sleeperAdp: 177,
        espnAdp: 182,
        yahooAdp: 129,
        nflAdp: 212,
        ffCheatsheetAdp: 0
    },
    {
        rank: 0,
        name: "Geno Smith",
        team: "LV",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 211,
        bye: 0,
        position: "QB",
        passingYards: 3625,
        passingTouchdowns: 20.25,
        interceptions: 9.5,
        rushingYards: 230,
        receivingYards: 0,
        touchdowns: 1,
        receptions: 0,
        fumbles: 1,
        sacks: 39,
        fantasyScore: 0,
        drafted: false,
        injury: "4%",
        averageAdp: 211,
        sleeperAdp: 213,
        espnAdp: 214,
        yahooAdp: 124,
        nflAdp: 197,
        ffCheatsheetAdp: 170
    },
    {
        rank: 0,
        name: "Adam Thielen",
        team: "CAR",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 183,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 5,
        receivingYards: 525,
        touchdowns: 4.25,
        receptions: 51.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "16%",
        averageAdp: 183,
        sleeperAdp: 170,
        espnAdp: 153,
        yahooAdp: 128,
        nflAdp: 206,
        ffCheatsheetAdp: 176
    },
    {
        rank: 0,
        name: "Marvin Mims Jr.",
        team: "DEN",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 159,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 40,
        receivingYards: 525,
        touchdowns: 4,
        receptions: 36.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "3%",
        averageAdp: 159,
        sleeperAdp: 141,
        espnAdp: 157,
        yahooAdp: 133,
        nflAdp: 171,
        ffCheatsheetAdp: 138
    },
    {
        rank: 0,
        name: "Jerome Ford",
        team: "CLE",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 164,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 0,
        touchdowns: 0,
        receptions: 0,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "9%",
        averageAdp: 164,
        sleeperAdp: 176,
        espnAdp: 143,
        yahooAdp: 130,
        nflAdp: 245,
        ffCheatsheetAdp: 0
    },
    {
        rank: 0,
        name: "Isaac Guerendo",
        team: "SF",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 153,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 450,
        receivingYards: 165,
        touchdowns: 4.25,
        receptions: 16.5,
        fumbles: 1,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "6%",
        averageAdp: 153,
        sleeperAdp: 153,
        espnAdp: 190,
        yahooAdp: 128,
        nflAdp: 176,
        ffCheatsheetAdp: 134
    },
    {
        rank: 0,
        name: "Tre' Harris",
        team: "LAC",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 150,
        bye: 0,
        position: "WR",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 575,
        touchdowns: 3.25,
        receptions: 44,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "10%",
        averageAdp: 150,
        sleeperAdp: 136,
        espnAdp: 172,
        yahooAdp: 131,
        nflAdp: 159,
        ffCheatsheetAdp: 133
    },
    {
        rank: 0,
        name: "Tyler Allgeier",
        team: "ATL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 167,
        bye: 0,
        position: "RB",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 575,
        receivingYards: 80,
        touchdowns: 2.75,
        receptions: 9,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "2%",
        averageAdp: 167,
        sleeperAdp: 175,
        espnAdp: 168,
        yahooAdp: 131,
        nflAdp: 173,
        ffCheatsheetAdp: 149
    },
    {
        rank: 0,
        name: "Kyle Pitts",
        team: "ATL",
        value: 0,
        tier: 0,
        scarcity: "",
        adp: 142,
        bye: 0,
        position: "TE",
        passingYards: 0,
        passingTouchdowns: 0,
        interceptions: 0,
        rushingYards: 0,
        receivingYards: 550,
        touchdowns: 3,
        receptions: 43.5,
        fumbles: 0,
        sacks: 0,
        fantasyScore: 0,
        drafted: false,
        injury: "10%",
        averageAdp: 142,
        sleeperAdp: 124,
        espnAdp: 141,
        yahooAdp: 125,
        nflAdp: 137,
        ffCheatsheetAdp: 139
    }
    ]);

    return (
        <AppContext.Provider value={{ pointValues, setPointValues, allPlayers, setAllPlayers, repLevels, setRepLevels, tiers, setTiers, adpSetting, setAdpSetting }}>
            {children}
        </AppContext.Provider>
    );
};

export { AppProvider, AppContext };